### ISSUE TITLE
Circle fires too many events

### ISSUE THREAD

**Issue by thebrownfox** [xon52/x5-gmaps#10] opened 2020-08-25 13:21 UTC
Event `circle_changed` is fired too many times (I guess for every pixel) in case I drag the circle not exactly in the center of the circle. When I drag the little dot, it's fired just once.

**Comment by xon52** [comment] 2020-08-25 21:22
I have just checked this and I am not finding it. Are you using the latest version (v0.3.20)?
I added a console log even to the example circle in the demo for when the center or radius is changed for you to compare:
[code](https://github.com/xon52/x5-gmaps/blob/master/example/ExampleShape.vue) [example](https://xon52.github.io/x5-gmaps/#rectanglesandcircles)

Let me know if that doesn't solve your problem.

**Comment by thebrownfox** [comment] 2020-08-26 09:04
@xon52 I think it's property draggable that causes this. However, it behaves similar if you drag the circle (via the point in its middle) and drag it out of bounds (visible area).

**Comment by xon52** [comment] 2020-08-26 09:13
@thefoxie can you share your relevant `<template>` code? I want to see which event you're listening to.

**Comment by thebrownfox** [comment] 2020-08-26 09:16
```vue
        <gmaps-circle
            v-for="(location, index) in newLocations"
            :key="index"
            :center="{ lat: location.lat, lng: location.lng }"
            :draggable="true"
            :radius="location.radius.default + location.radius.added"
            :editable="true"
            stroke-color="#7499be"
            stroke-weight="1.5"
            fill-color="#7499be"
            fill-opacity="0.2"
            @centerChanged="changeCenter(location, $event)"
            @radiusChanged="changeRadius(location, $event)"
            @click="circleEvent($event, location, index)"
        />
```

**Comment by xon52** [comment] 2020-08-26 09:29
Ah, I think I see the issue. I think what's happening is your `changeRadius(location, $event)` changes the `location.radius.default` which triggers `@radiusChanged`.
It may also because `location.radius.added` adds something above the threshold (which is 1.0) that it triggers it. You may have to put some logic in to break that cycle like an `updating` property which it triggers and checks before running.

**Comment by thebrownfox** [comment] 2020-08-26 09:35
@xon52 no that's not the issue. I mean dragging around not changing radius. It happens even when I remove those. Go to devtools and drag them around and you will see what I'm talking about. Or wait I will make gif and share it. Give me couple of minutes.

**Comment by xon52** [comment] 2020-08-26 09:50
I can see an odd behaviour when dragging it to the edge of the screen and it moves the map. It looks like it's recording`boundsChanged` and `centerChanged` while the map moves - but they aren't actually firing my methods attached to them which is unexpected. I will have to have a closer look.

**Comment by xon52** [comment] 2020-08-26 09:53
Ah, OK. I understand. Dragging the circle causes it the `centerChanged` event. Unfortunately, that is by design. I will have a think about if I can make the resolution it records a change variable. At the moment it is a change of 0.001 which may be too fine.

The issue is the resolution you want really depends on the map zoom. Maybe I can make it dependent on that.

**Comment by thebrownfox** [comment] 2020-08-26 10:15
@xon52 here it is https://cloud.foxie.sk/s/qLZrdMxb9Jf7TY5

**Comment by xon52** [comment] 2020-08-26 10:37
@thefoxie can you explain how this is affecting performance or something else?
All I am doing is passing on Google Maps change events - I am not creating new events. I have throttled the `radiusChanged` and `centerChanged` events, and I can do the same to `drag` event but I think if it is a performance issue it will become slower as it will do a maths calculation every time the event fire anyway to find out if it should bubble the event to you.
My problem is knowing how much sensitivity it has. I think Google has made it too sensitive, but I do not want to disadvantage people who want to know if the pin is moved by 1m.

**Comment by thebrownfox** [comment] 2020-08-26 10:47
@xon52 I know, it depends on usecase. You cannot see it in the video but it creates a delay (and stutters) when there's method attached to the event. This might be because I use the event to update the circle itself + it bubbles up via event bus to parent component. As you said the delay might work better maybe. Not sure if users would drago those things crazy like that but I just noticed.

**Comment by xon52** [comment] 2020-08-26 10:50
OK thanks for telling me. I didn't see `@drag` causes so many events. I will test if performance is improved by throttling it like I do with `radiusChanged` and `centerChanged`.

**Comment by xon52** [comment] 2020-08-27 12:02
@thefoxie So I have spent most of today trying to fix this issue and decided that I won't be fixing this until the next major release - but I want to explain why because I really value your input and agree it's something that can be improved - if you're interested.

As I mentioned before, I'm just passing the Google Map events into Vue - I do not add any more events on top of Google Maps. There will be some overhead using Vue, but it's really small.

Now I did fix it, but removed my solution for 3 reasons:
1. The solution only stopped the events being emitted - it did not remove the events. To stop them being emitted, I needed to add maths checks and data properties. This is more JS and Vue overhead.
2. The problem also exists for any object you can move (Polylines, Marker, etc) even when you just move around on the map (`boundsChanged` and `centerChanged` events).
3. The Maths I used to test whether the move was enough depends on the zoom level, and then uses an empirically derived formula `minimum_lat_change = 3.3 * Math.E ** (-0.6 * zoom)` - which is not perfect and is my own preference but everyone will have their own.

Instead, I hope you can put a throttle in yourself to make sure that your method attached to the event only fires if there is a big enough change in value.

I will try again when I eventually rewrite this because I agree that it fires too many events.

**Closed as completed by xon52** 2020-08-27 12:02 UTC
Labels: wontfix, revisit next major release

**Comment by thebrownfox** [comment] 2020-08-28 09:08
@xon52 I really appreciate the time you invested in solving the issue and I understand your point of view. As I mentioned, it doesn't have to be such a big deal as users don't move around the point/circle/marker that much and frequently. I just noticed it because that's what devs do when they develop something, we push things to the limits. I will gladly help you with this, I've just been busy recently ;)
